//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PacmanGame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PacmanGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a {
            get {
                object obj = ResourceManager.GetObject("a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b {
            get {
                object obj = ResourceManager.GetObject("b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eweder {
            get {
                object obj = ResourceManager.GetObject("eweder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap left {
            get {
                object obj = ResourceManager.GetObject("left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 111111111111111111111111
        ///1000000000000000000000p1
        ///111111111111111111111111.
        /// </summary>
        internal static string level1 {
            get {
                return ResourceManager.GetString("level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1111111111111111111111111
        ///1000000000000000000000001
        ///1011111110101010111111101
        ///100000000d10e01*000000001
        ///11111111111t1t11111111111
        ///1000000000001000000000001
        ///1011111111101011111111101
        ///1000000000001000000000001
        ///1011111011101011101111101
        ///1011111011101011101111101
        ///1011111011101011101111101
        ///1e000000000000000000000p1
        ///111111111111t111111111111
        ///111111111111t111111111111
        ///1000000000000000000000001
        ///1011111110101010111111101
        ///100000000d10e01*000000001
        ///11111111111t1t11111111111
        ///1000000000001000000000001        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level2 {
            get {
                return ResourceManager.GetString("level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 111111111111111111111
        ///1e0000000000000000001
        ///101111111010111111101
        ///101111*00010000111101
        ///101111011010110111101
        ///100000000000000000001
        ///111111111t1t111111111
        ///100000000000000000001
        ///101111011010110111101
        ///101111000010000111101
        ///101111111010111111101
        ///1e00000000000000000p1
        ///111111111111111111111.
        /// </summary>
        internal static string level25 {
            get {
                return ResourceManager.GetString("level25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 111111111111111111111
        ///100000000000000000001
        ///101111111010111111101
        ///101111000010000111101
        ///101111011010110111101
        ///1e00000110101100000e1
        ///101111111010111111101
        ///100000000000000000001
        ///101111111010111111101
        ///100000011010110000001
        ///101111011010110111101
        ///101111*00010000111101
        ///101111111010111111101
        ///1000000000000000000p1
        ///111111111111111111111.
        /// </summary>
        internal static string level3 {
            get {
                return ResourceManager.GetString("level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 111111111111111111111
        ///1e00000000100000000e1
        ///101011111010111110101
        ///101000000010000000101
        ///101111111111111111101
        ///100000000000000000001
        ///111111111101111111111
        ///1000000000p0000000001
        ///101111111010111111101
        ///100000011010110000001
        ///101011111010111110101
        ///101000000010000000101
        ///101110111010111011101
        ///1000000000000000000e1
        ///111111111111111111111.
        /// </summary>
        internal static string level4 {
            get {
                return ResourceManager.GetString("level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11111111111111111111111111111111111111111111111111
        ///100000000000000000000000p0000000000000000000000001
        ///11111111111111111111111111111111111111111111111111.
        /// </summary>
        internal static string level99 {
            get {
                return ResourceManager.GetString("level99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NoSound {
            get {
                object obj = ResourceManager.GetObject("NoSound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PacmenToWaiter {
            get {
                object obj = ResourceManager.GetObject("PacmenToWaiter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap right {
            get {
                object obj = ResourceManager.GetObject("right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sound {
            get {
                object obj = ResourceManager.GetObject("sound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap star {
            get {
                object obj = ResourceManager.GetObject("star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
